# **NUMPY CRASH COURSE**

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
import sys
sys.version

'3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]'

# **CREATING ARRAY**

In [ ]:
mylist = [0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [ ]:
np.array

In [ ]:
 np.empty(2)

array([-5.73021895e-300,  6.80752465e-310])

In [ ]:
type(mylist)

list

In [ ]:
arr=np.array(mylist)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4.0)

array([0., 1., 2., 3.])

In [ ]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,10) #First argument should be less than second argument

array([], dtype=int64)

In [ ]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
ary = np.arange(-30,20)
ary

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [ ]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(10,30,5,4) # Only start,stop and step allowed or not more than 3 argument

TypeError: Cannot interpret '4' as a data type

# np.zeros - by default first argument is raw & second argument is column

In [ ]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(-5)

ValueError: negative dimensions are not allowed

In [ ]:
np.zeros(10, dtype='int') # hyperparameter tunning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,2), dtype=int)  # two dimension array

array([[0, 0],
       [0, 0]])

In [ ]:
zero = np.zeros([2,2])
zero

array([[0., 0.],
       [0., 0.]])

In [ ]:
print(type(zero))

<class 'numpy.ndarray'>


In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
n = (6,7)
n1 = (5,6)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros(n1, dtype=int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


**np.ones**

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [ ]:
np.ones(4,dtype=float)

array([1., 1., 1., 1.])

In [ ]:
np.ones(4,dtype=str)

array(['1', '1', '1', '1'], dtype='<U1')

In [ ]:
np.ones(4,dtype=bool)

array([ True,  True,  True,  True])

In [ ]:
np.ones(4,dtype=complex)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [ ]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

**RAND**

In [ ]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
import numpy as np

In [ ]:
np.random.rand(3,2)

array([[0.23860898, 0.9173841 ],
       [0.8905532 , 0.46377088],
       [0.08694342, 0.657155  ]])

In [ ]:
np.random.rand(5)

array([0.74338585, 0.94237745, 0.7052683 , 0.42260996, 0.70287252])

In [ ]:
np.random.rand(3,5)

array([[0.90472404, 0.31079411, 0.96910006, 0.67716544, 0.3441798 ],
       [0.51101747, 0.58780128, 0.34109196, 0.87705659, 0.35910381],
       [0.06389239, 0.66630768, 0.11768862, 0.75566198, 0.44661562]])

In [ ]:
 np.random.randint(2,5)

4

In [ ]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
 np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
 np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 13, 11, 12],
       [19, 13, 18, 15],
       [12, 16, 18, 11],
       [11, 13, 18, 16],
       [13, 18, 16, 16]])

In [ ]:
np.random.randint(1,40,(10,10))

array([[ 3,  1, 30,  1, 24, 36,  5,  7,  1, 27],
       [29, 14, 33, 22, 21, 27, 16, 10, 10, 22],
       [ 7, 17, 35,  2, 14,  3,  3, 28, 19,  4],
       [26, 22, 37, 16, 12, 10, 11, 24,  6, 37],
       [13, 33, 25, 39,  3,  9, 31, 18, 20, 28],
       [21, 14,  3, 22, 33, 33,  2, 23, 38, 26],
       [36, 22, 22,  5,  4, 20, 21, 13, 38, 34],
       [ 1, 11, 34, 26, 28, 39, 15, 12,  7, 37],
       [21, 14,  4, 15, 14, 34, 34, 18, 19, 36],
       [32, 26, 23, 24, 18, 13, 35, 26,  9, 18]])

In [ ]:
np.random.randint(1,100,(12,12))

array([[56, 62, 61, 45, 47, 21,  2, 84, 10, 98, 49, 60],
       [98, 47, 66, 37, 25, 58,  3, 82, 57,  8, 85, 61],
       [17, 55, 89, 62, 95,  6, 85, 58, 47, 62, 88, 69],
       [12, 89, 80, 86, 81, 28, 31,  3, 33, 59, 52,  1],
       [89, 23, 46,  4, 42, 27, 81, 24, 69, 46, 17, 69],
       [98,  2, 51, 67, 32, 74,  3, 66, 12, 66,  6, 27],
       [39, 76, 50, 80, 36, 79, 50, 49, 46, 18, 24, 99],
       [36, 42, 34, 83, 39,  2, 34, 56, 16, 88, 50, 44],
       [46, 52, 14, 71, 33, 58, 53, 53, 78, 68, 54, 98],
       [30, 78,  2, 84, 75, 60, 96, 93, 90, 14,  6, 25],
       [79,  8, 37, 90, 78, 94, 20, 16, 93, 69, 30, 92],
       [88,  9, 47, 36, 61, 26, 81, 65, 26, 60, 72, 64]])

In [ ]:
np.random.rand(20,30,10)

array([[[0.96833922, 0.9084338 , 0.41817429, ..., 0.00664562,
         0.0025291 , 0.24495958],
        [0.28302869, 0.83386483, 0.53829322, ..., 0.86150156,
         0.48450097, 0.72187091],
        [0.49653132, 0.6679883 , 0.85779988, ..., 0.31724976,
         0.70992218, 0.31648253],
        ...,
        [0.99607589, 0.5204048 , 0.39113264, ..., 0.54142501,
         0.02933257, 0.8330415 ],
        [0.25076285, 0.28378067, 0.88057147, ..., 0.70953674,
         0.94428334, 0.1685509 ],
        [0.01334929, 0.67065301, 0.48974589, ..., 0.92543823,
         0.80634354, 0.5970362 ]],

       [[0.00607076, 0.99563573, 0.88435594, ..., 0.55120921,
         0.68111287, 0.05341332],
        [0.6001298 , 0.86070565, 0.07796751, ..., 0.33739938,
         0.54236179, 0.46516765],
        [0.06122773, 0.89535592, 0.67944271, ..., 0.15722635,
         0.14604205, 0.55363237],
        ...,
        [0.69372877, 0.24257385, 0.26316192, ..., 0.21375997,
         0.12637346, 0.11825361],
        [0.5

In [ ]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.random.randint(10,20,(5,4))

array([[11, 15, 19, 15],
       [18, 12, 15, 16],
       [15, 16, 19, 15],
       [11, 12, 18, 10],
       [17, 13, 13, 15]])

# Slicing in matrix

In [ ]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 17, 11, 12],
       [19, 18, 12, 18],
       [18, 16, 17, 18],
       [19, 11, 10, 13],
       [11, 11, 16, 12]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b[:]

array([[16, 17, 11, 12],
       [19, 18, 12, 18],
       [18, 16, 17, 18],
       [19, 11, 10, 13],
       [11, 11, 16, 12]])

In [ ]:
b[1:3]

array([[19, 18, 12, 18],
       [18, 16, 17, 18]])

In [ ]:
b[1,2]

12

In [ ]:
b[1,-1]

18

In [ ]:
b[2:4]

array([[18, 16, 17, 18],
       [19, 11, 10, 13]])

In [ ]:
b[0:-2]

array([[16, 17, 11, 12],
       [19, 18, 12, 18],
       [18, 16, 17, 18]])

In [ ]:
b[-4,2]

12

In [ ]:
b[:]

array([[16, 17, 11, 12],
       [19, 18, 12, 18],
       [18, 16, 17, 18],
       [19, 11, 10, 13],
       [11, 11, 16, 12]])

In [ ]:
b[:3]

array([[16, 17, 11, 12],
       [19, 18, 12, 18],
       [18, 16, 17, 18]])

In [ ]:
b[2:]

array([[18, 16, 17, 18],
       [19, 11, 10, 13],
       [11, 11, 16, 12]])

In [ ]:
b[::2]

array([[16, 17, 11, 12],
       [18, 16, 17, 18],
       [11, 11, 16, 12]])

In [ ]:
b[::-3]

array([[11, 11, 16, 12],
       [19, 18, 12, 18]])

In [ ]:
mat = np.arange(0,100).reshape(10,10)

In [ ]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
row = 4
col = 5

In [ ]:
col

5

In [ ]:
row

4

In [ ]:
mat[row,col]

45

In [ ]:
mat[4,5]

45

In [ ]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
col = 6

In [ ]:
mat[6] # bydefault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
mat[col,:]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [ ]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [ ]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [ ]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [ ]:
row

4

In [ ]:
col

6

In [ ]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [ ]:
mat[1,4]


14

In [ ]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [ ]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[:6]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [ ]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [ ]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[0,1]

1

In [ ]:
mat[1,6]

16

In [ ]:
mat[1:2,2:4]

array([[12, 13]])

# **operations**

In [ ]:
a = np.random.randint(10,20)
a

10

In [ ]:
a = np.random.randint(10,20,10)
a

array([15, 15, 15, 10, 15, 17, 12, 19, 13, 16])

In [ ]:
arr2 = np.random.randint(10,20,(10,10))
arr2

array([[13, 13, 17, 18, 18, 12, 15, 10, 12, 14],
       [16, 16, 11, 17, 17, 15, 12, 11, 16, 12],
       [14, 16, 13, 18, 16, 18, 19, 13, 12, 14],
       [15, 16, 15, 15, 13, 15, 19, 18, 18, 17],
       [13, 12, 14, 16, 17, 16, 18, 15, 17, 12],
       [16, 12, 10, 13, 10, 14, 10, 11, 16, 11],
       [13, 10, 13, 11, 13, 19, 16, 14, 11, 16],
       [11, 17, 13, 15, 19, 18, 13, 10, 10, 12],
       [14, 14, 16, 12, 16, 13, 15, 12, 15, 13],
       [15, 17, 16, 15, 18, 16, 12, 10, 17, 11]])

In [ ]:
id(arr2)

133712457180496

In [ ]:
arr2[::-1]

array([[15, 17, 16, 15, 18, 16, 12, 10, 17, 11],
       [14, 14, 16, 12, 16, 13, 15, 12, 15, 13],
       [11, 17, 13, 15, 19, 18, 13, 10, 10, 12],
       [13, 10, 13, 11, 13, 19, 16, 14, 11, 16],
       [16, 12, 10, 13, 10, 14, 10, 11, 16, 11],
       [13, 12, 14, 16, 17, 16, 18, 15, 17, 12],
       [15, 16, 15, 15, 13, 15, 19, 18, 18, 17],
       [14, 16, 13, 18, 16, 18, 19, 13, 12, 14],
       [16, 16, 11, 17, 17, 15, 12, 11, 16, 12],
       [13, 13, 17, 18, 18, 12, 15, 10, 12, 14]])

In [ ]:
arr2[::-2]

array([[15, 17, 16, 15, 18, 16, 12, 10, 17, 11],
       [11, 17, 13, 15, 19, 18, 13, 10, 10, 12],
       [16, 12, 10, 13, 10, 14, 10, 11, 16, 11],
       [15, 16, 15, 15, 13, 15, 19, 18, 18, 17],
       [16, 16, 11, 17, 17, 15, 12, 11, 16, 12]])

In [ ]:
arr2[::-3]

array([[15, 17, 16, 15, 18, 16, 12, 10, 17, 11],
       [13, 10, 13, 11, 13, 19, 16, 14, 11, 16],
       [15, 16, 15, 15, 13, 15, 19, 18, 18, 17],
       [13, 13, 17, 18, 18, 12, 15, 10, 12, 14]])

In [ ]:
arr2[3:]

array([[15, 16, 15, 15, 13, 15, 19, 18, 18, 17],
       [13, 12, 14, 16, 17, 16, 18, 15, 17, 12],
       [16, 12, 10, 13, 10, 14, 10, 11, 16, 11],
       [13, 10, 13, 11, 13, 19, 16, 14, 11, 16],
       [11, 17, 13, 15, 19, 18, 13, 10, 10, 12],
       [14, 14, 16, 12, 16, 13, 15, 12, 15, 13],
       [15, 17, 16, 15, 18, 16, 12, 10, 17, 11]])

In [ ]:
arr2

array([[13, 13, 17, 18, 18, 12, 15, 10, 12, 14],
       [16, 16, 11, 17, 17, 15, 12, 11, 16, 12],
       [14, 16, 13, 18, 16, 18, 19, 13, 12, 14],
       [15, 16, 15, 15, 13, 15, 19, 18, 18, 17],
       [13, 12, 14, 16, 17, 16, 18, 15, 17, 12],
       [16, 12, 10, 13, 10, 14, 10, 11, 16, 11],
       [13, 10, 13, 11, 13, 19, 16, 14, 11, 16],
       [11, 17, 13, 15, 19, 18, 13, 10, 10, 12],
       [14, 14, 16, 12, 16, 13, 15, 12, 15, 13],
       [15, 17, 16, 15, 18, 16, 12, 10, 17, 11]])

In [ ]:
arr2.max()

19

In [ ]:
arr2.min()

10

In [ ]:
help()

Welcome to Python 3.11's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.11/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q" or "quit".

help> q

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [ ]:
arr2.sum()

1433

In [ ]:
arr2.mean()

14.33

In [ ]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [ ]:
# # Without work on import* can you please find the median, mode)

In [ ]:
arr2

array([[13, 13, 17, 18, 18, 12, 15, 10, 12, 14],
       [16, 16, 11, 17, 17, 15, 12, 11, 16, 12],
       [14, 16, 13, 18, 16, 18, 19, 13, 12, 14],
       [15, 16, 15, 15, 13, 15, 19, 18, 18, 17],
       [13, 12, 14, 16, 17, 16, 18, 15, 17, 12],
       [16, 12, 10, 13, 10, 14, 10, 11, 16, 11],
       [13, 10, 13, 11, 13, 19, 16, 14, 11, 16],
       [11, 17, 13, 15, 19, 18, 13, 10, 10, 12],
       [14, 14, 16, 12, 16, 13, 15, 12, 15, 13],
       [15, 17, 16, 15, 18, 16, 12, 10, 17, 11]])

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(0,10,(5,4))
arr

array([[0, 4, 5, 6],
       [4, 5, 7, 8],
       [9, 2, 8, 3],
       [0, 9, 5, 2],
       [5, 0, 3, 9]])

In [ ]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.reshape(20,1) # 20 rows, 1 column (20*1=20)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

## Masking

In [ ]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
id(mat)

139607338612176

In [ ]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
mat[mat==50]

array([50])

In [ ]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
a2 = mat[mat>50]
a2


array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
# # python program to generat otp

In [ ]:
import random

def generate_otp(length=6):
    """Generate a numeric OTP of a specified length."""
    digits = '01234567'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 6216


In [ ]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [ ]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x7ef8c4e85ac0>


In [ ]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]


In [ ]:
# number system conversion (bit-binary digit)

In [ ]:
15

15

In [ ]:
bin(25)

'0b11001'

In [ ]:
int(0b1111)

15

In [ ]:
bin(10)

'0b1010'

In [ ]:
oct(15)

'0o17'

In [ ]:
hex(15)

'0xf'

In [ ]:
hex(10)

'0xa'

In [ ]:
# variable swapping

In [ ]:
a  = 3
b = 5

In [ ]:
temp = a
a=b
b= temp

In [ ]:
print(a)
print(b)

5
3


In [ ]:
a = a+b
b = a-b
a = a-b

In [ ]:
print(a)
print(b)

3
5


In [1]:
# array creation
import numpy as np

In [3]:
# Create an array from a list
a = np.array([1, 2, 3])
print( a)

[1 2 3]


In [7]:
# Create an array with evenly spaced values
b = np.arange(0, 20, 2)  # Values from 0 to 20 with step 2
print(b)

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
# Create an array with linearly spaced values
c = np.linspace(1, 10, 5)  # 5 values evenly spaced between 0 and 1
print("Array c:", c)

Array c: [ 1.    3.25  5.5   7.75 10.  ]


In [12]:
# Create an array filled with ones
e = np.ones((3, 5))  # 3x5 array of ones
print("Array e:\n", e)

Array e:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# Create an identity matrix
f = np.eye(4)  # 4x4 identity matrix
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# array minipulation funcations

In [23]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1,3))  # Reshape to 1x3
print(reshaped)

[[1 2 3]]


In [24]:
a2= np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(a2)

[[1 2 3]
 [4 5 6]]


In [25]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [26]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [ ]:
# maths funcations

In [28]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [29]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [30]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [31]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [32]:
# Dot product of two arrays
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)  # Dot product of a and g
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [33]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [34]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


In [ ]:
# statistics funcations

In [35]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [36]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [37]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [38]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [39]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


In [ ]:
# linear algebra funcations

In [40]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

In [41]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [42]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# random sampaling uncations

In [43]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.67859315 0.16712307 0.88625227]


In [44]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [45]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [46]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


In [ ]:
# Boolean & Logical Funcations

In [47]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [48]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [49]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [50]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


In [ ]:
# SET Opeartiona

In [51]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [52]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


In [ ]:
# Array Attribute Funcations

In [53]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


In [ ]:
# Other Funcations

In [54]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [55]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [56]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
